config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :posts do
      get 'toggle-published' => 'posts#toggle_published', as: :toggle_published, on: :member
    end
    resources :comments, only: [:index, :destroy]
    get '/' => 'posts#index', as: :root
  end

  resources :posts, only: [:index, :show] do
    resources :comments
  end

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments

  validates :title, presence: true,
              length: { minimum: 2 }

  scope :published, -> { where(published: true) }
  scope :find_by_title, ->(search) { where("title LIKE ?", "%#{search}%") }
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'admin'

  http_basic_authenticate_with name: "admin", password: "secret"
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::AdminController
  before_action :set_comment, only: [:destroy]

  # GET admin/comments
  # GET admin/comments.json
  def index
    @comments = Comment.all
  end

  # DELETE admin/comments/1
  # DELETE admin/comments/1.json
  def destroy
    @comment.destroy
    @comments = Comment.all

    respond_to do |format|
      format.html { redirect_to admin_comments_url, notice: 'Comment was successfully destroyed.' }
      format.js {}
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :toggle_published]
  helper_method :sort_column, :sort_direction

  # GET admin/posts
  # GET admin/posts.json
  def index
    if params[:search]
      @posts = Post.find_by_title(params[:search]).order(sort_column + " " + sort_direction)
    else
      @posts = Post.all.order(sort_column + " " + sort_direction)
    end
  end

  # GET admin/posts/1
  # GET admin/posts/1.json
  def show
  end

  # GET admin/posts/new
  def new
    @post = Post.new
  end

  # GET admin/posts/1/edit
  def edit
  end

  # POST admin/posts
  # POST admin/posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: admin_post_url(@post.errors), status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT admin/posts/1
  # PATCH/PUT admin/posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to admin_post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: admin_post_url(@post.errors), status: :unprocessable_entity }
      end
    end
  end

  # DELETE admin/posts/1
  # DELETE admin/posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_published
    @post.published = !@post.published
    @post.save

    redirect_to admin_post_url(@post)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :published)
    end

    # Sort expense table : Get column. Use in controller and helper(set table header)
    def sort_column
      Post.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
    end
    
    # Sort expense table : Get direction. Use in controller and helper(set table header)
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  # POST /comments
  def create
    @comment = @post.comments.create! comment_params
    CommentsMailer.submitted(@comment).deliver_later
    
    respond_to do |format|
      format.html { redirect_to @post }
      format.js {}
    end
  end

  private
    def set_post
      @post = Post.find(params[:post_id])
    end
    
    def comment_params
      params.require(:comment).permit(:content, :author)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  def index
    @posts = Post.published
  end

  # GET /post/1
  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
  # Set table header to sorting link
  def sortable(column, title = nil)
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    
    if not(css_class.nil?)
      icon_direction = sort_direction == "asc" ? "<i class='fa fa-caret-up'></i>" : "<i class='fa fa-caret-down'></i>"
    end
    
    title ||= column.titleize + " #{icon_direction}"
    link_to title.html_safe, { sort: column, direction: direction }, { class: css_class }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/comments/_comment.html.erb
<li>
  <span>
    <strong><%= comment.author %></strong>
    <span><%= comment.created_at.to_s(:long) %></span>
    <small><%= link_to 'Destroy', admin_comment_path(comment), method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></small>
  </span>
  <p><%= comment.content %></p>
</li>

app/views/admin/comments/destroy.js.erb
$("#comments").html("<%= escape_javascript(render @comments) %>");

app/views/admin/comments/index.html.erb
<p id="notice"><%= notice %></p>

<ul class="breadcrumb">
  <li>Blog Admin</li>
  <li class="active">Comments</li>
</ul>

<ul id="comments" class="comments u-full-width">
  <%= render @comments %>
</ul>

app/views/admin/posts/_form.html.erb
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>

<% if post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<br>
<div class="field">
  <strong>Published:</strong> <%= f.check_box :published %>
</div>

<div class="field">
  <%= f.text_field :title, placeholder: :title, class:"title" %>
</div>

<div class="field">
  <%= f.label :content, class: "content" %>
  <%= f.text_area :content, id: "post-content", style: "height: 350px;" %>
</div>

<script>
  tinymce.init({
    selector:'#post-content',
    plugins : [
      'advlist autolink link image lists charmap preview hr anchor pagebreak spellchecker',
      'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
      'save table contextmenu directionality paste textcolor'
    ],
    toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media | forecolor backcolor | preview code fullscreen'
  });
</script>

app/views/admin/posts/_post.html.erb
<tr>
  <td>
    <% css_class = post.published ? "check-square-o" : "square-o" %>
    <i class="fa fa-<%= css_class %>"></i>
  </td>
  <td><%= post.created_at.to_s(:long) %></td>
  <td><%= link_to post.title, admin_post_path(post) %></td>
  <td><%= strip_tags "#{post.content[0..70]}..." %></td>
</tr>

app/views/admin/posts/edit.html.erb
<ul class="breadcrumb">
  <li>Blog Admin</li>
  <li><%= link_to 'Posts', admin_posts_path %></li>
  <li class="active">Editing <%= @post.title %></li>
</ul>

<fieldset>
  <legend><h4>Editing post</h4></legend>
  <%= form_for :post, url: admin_post_path(@post), method: :patch do |f| %>
    <%= render partial: "form", locals: { f: f, post: @post } %>
    <br>
    <div class="actions">
      <%= link_to 'Cancel', admin_post_path(@post), class: "button" %>
      <%= f.submit class: "button-primary" %>
    </div>
  <% end %>
</fieldset>

app/views/admin/posts/index.html.erb
<p id="notice"><%= notice %></p>

<ul class="breadcrumb">
  <li>Blog Admin</li>
  <li class="active">Posts</li>
  <li><%= link_to 'New Post', new_admin_post_path, "data-turbolinks": "false" %></li>
</ul>

<section class="searchfield text-right">
  <%= form_tag admin_posts_url, method: 'GET' do |f| %>
    <%= text_field_tag :search, params[:search], { placeholder: "Search by title..." } %>
    <%= submit_tag("Search") %>
  <% end %>
</section>

<table class="u-full-width">
  <thead>
    <tr>
      <th><%= sortable 'published' %></th>
      <th><%= sortable 'created_at' %></th>
      <th><%= sortable 'title' %></th>
      <th>Content</th>
    </tr>
  </thead>

  <tbody>
    <%= render @posts %>
  </tbody>
</table>

app/views/admin/posts/new.html.erb
<ul class="breadcrumb">
  <li>Blog Admin</li>
  <li><%= link_to 'Posts', admin_posts_path %></li>
  <li class="active">New Post</li>
</ul>

<fieldset>
  <legend><h4>New post</h4></legend>
  <%= form_for :post, url: admin_posts_path do |f| %>
    <%= render partial: "form", locals: { f: f, post: @post } %>
    <br>
    <div class="actions">
      <%= link_to 'Cancel', admin_posts_path, class: "button" %>
      <%= f.submit class: "button-primary" %>
    </div>
  <% end %>
</fieldset>

app/views/admin/posts/show.html.erb
<p id="notice"><%= notice %></p>

<ul class="breadcrumb">
  <li>Blog Admin</li>
  <li><%= link_to 'Posts', admin_posts_path %></li>
  <li class="active"><%= @post.title %></li>
</ul>

<div class="actions u-pull-right">
  <%= link_to toggle_published_admin_post_path(@post), class: "button" do %>
    <%= @post.published ? "Unpublish" : "Publish" %>
  <% end %>
  <%= link_to edit_admin_post_path(@post), "data-turbolinks": "false", class: "button" do %>
    <i class="fa fa-pencil" aria-hidden="true"></i>
    Edit
  <% end %>
  <%= link_to admin_post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: "button button-red" do %>
    <i class="fa fa-trash" aria-hidden="true"></i>
    Destroy
  <% end %>
</div>

<h4>
  <%= @post.title %>
  <% css_class = @post.published ? "eye" : "eye-slash" %>
  <i class="fa fa-<%= css_class %>" aria-hidden="true"></i>
</h4>

<p>
  <%= raw @post.content %>
</p>

app/views/comments/_comment.html.erb
<p class="comment">
  <%= comment.content %><br>
  <small>
    By <strong><%= comment.author %></strong>
    – <%= distance_of_time_in_words_to_now(comment.created_at) %>
  </small>
</p>

app/views/comments/_new.html.erb
<%= form_for [@post, Comment.new], remote: true do |f| %>
  <div class="field">
    <label>Your name:</label>
    <%= f.text_field :author, id: "comment-author", class: "u-full-width" %>
  </div>
  <div class="field">
    <label>Your comment:</label>
    <%= f.text_area :content, id: "comment-content", class: "u-full-width" %>
  </div>
  <div class="actions">
    <%= f.submit class: "button-primary" %>
  </div>
<% end %>

app/views/comments/create.js.erb
$("#comments").append("<%= escape_javascript(render @comment) %>");

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
  </head>

  <body>
    <header>
      <div class="container text-right">
        <%= link_to 'Posts', admin_posts_path %> |
        <%= link_to 'Comments', admin_comments_path %> |
        <%= link_to 'Go to blog', root_path %>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
  </head>

  <body>
    <header>
      <div class="container text-right">
        <%= link_to 'Manage blog', admin_root_path %>
      </div>
    </header>
    <div class="container">
      <h1 class="text-center">BLOG</h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h2>Posts</h2>

<ul class="posts">
  <% @posts.each do |post| %>
    <li class="post">
      <span class="date"><%= post.created_at.to_date %></span>
      <span class="title"><%= link_to post.title, post %></span>
    </li>
  <% end %>
</ul>

app/views/posts/show.html.erb
<ul class="breadcrumb">
  <li>Blog</li>
  <li><%= link_to 'Posts', posts_path %></li>
  <li class="active"><%= @post.title %></li>
</ul>

<article>
  <header>
    <h2><%= @post.title %></h2>
  </header>
  <section class="content">
    <p>
      <%= raw @post.content %>
    </p>
  </section>
  <section id="comments" class="comments">
    <h3>Comments</h3>
    <%= render @post.comments %>
  </section>
  <section class="new-comment">
    <%= render "comments/new", post: @post %>
  </section>
</article>